name: Release new version of addon

env:
  # Must match the name of your TOC file for WoW to load this addon at all
  ADDON_NAME: 
  # The list of what you want to ship in your ZIP file, minus the TOC which is required
  ADDON_BUNDLE_FILES: core.lua LICENSE README.md
  # The ID number for WoW Interface to be able to upload
  WOWI_ID: 

on:
  workflow_dispatch:
    # Enables a button to manually run this against the main branch
    branches: [ main ]
  push:
    # Enables automatic deploys off pushes/merges into the main branch
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Create 'dist' folder
      run: mkdir ${{env.ADDON_NAME}}/

    - name: Put everything into a folder
      run: cp -r ${{ env.ADDON_BUNDLE_FILES }} ${{ env.ADDON_NAME }}.toc ${{env.ADDON_NAME}}/
  
    - name: Zip it good
      run: zip -9 -r ${{env.ADDON_NAME}}.zip  ${{env.ADDON_NAME}}/
      
    - name: Parse WoW Addon Verions
      id: get_versions
      uses: icbat/parse-wow-addon-version@v0.0.1
      with:
        tocfile: ${{ env.ADDON_NAME }}.toc
    
    - name: Upload to WoW Interface
      uses: icbat/wow-addon-upload-action@v0.0.4
      with:
        id: ${{ env.WOWI_ID }}
        zipFilePath: ${{ env.ADDON_NAME }}.zip
        compatible: ${{ steps.get_versions.outputs.supported_version }}
        version: ${{ steps.get_versions.outputs.addon_version }}
        apiKey: ${{ secrets.WOW_INTERFACE }}
